In [1]:
import pandas_datareader as data
from bokeh.plotting import figure,output_file,show

import datetime
start=datetime.datetime(2019,1,1)
end=datetime.datetime(2019,1,10)

df=data.DataReader(name="GOOG",data_source="yahoo",start=start,end=end)

In [2]:
df

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2018-12-31,1052.699951,1023.590027,1050.959961,1035.609985,1493300,1035.609985
2019-01-02,1052.319946,1015.710022,1016.570007,1045.849976,1532600,1045.849976
2019-01-03,1056.979980,1014.070007,1041.000000,1016.059998,1841100,1016.059998
2019-01-04,1070.839966,1027.417969,1032.589966,1070.709961,2093900,1070.709961
2019-01-07,1074.000000,1054.760010,1071.500000,1068.390015,1981900,1068.390015
2019-01-08,1084.560059,1060.530029,1076.109985,1076.280029,1764900,1076.280029
2019-01-09,1082.630005,1066.400024,1081.650024,1074.660034,1199300,1074.660034
2019-01-10,1071.150024,1057.709961,1067.660034,1070.329956,1456400,1070.329956

In [3]:
def inc_dec(c,o):
    if c>o:
        value="Increase"
    elif c<o:
        value="Decrease"
    else:
        value="Equal"
    return value

df["Status"]=[inc_dec(c,o) for c,o in zip(df.Close,df.Open)]

In [4]:
df["Middle"]=(df.Close+df.Open)/2

In [5]:
df["Hight"]=abs(df.Close-df.Open)

df

,High,Low,Open,Close,Volume,Adj Close,Status,Middle,Hight
Date,,,,,,,,,
2018-12-31,1052.699951,1023.590027,1050.959961,1035.609985,1493300,1035.609985,Decrease,1043.284973,15.349976
2019-01-02,1052.319946,1015.710022,1016.570007,1045.849976,1532600,1045.849976,Increase,1031.209991,29.279968
2019-01-03,1056.979980,1014.070007,1041.000000,1016.059998,1841100,1016.059998,Decrease,1028.529999,24.940002
2019-01-04,1070.839966,1027.417969,1032.589966,1070.709961,2093900,1070.709961,Increase,1051.649963,38.119995
2019-01-07,1074.000000,1054.760010,1071.500000,1068.390015,1981900,1068.390015,Decrease,1069.945007,3.109985
2019-01-08,1084.560059,1060.530029,1076.109985,1076.280029,1764900,1076.280029,Increase,1076.195007,0.170044
2019-01-09,1082.630005,1066.400024,1081.650024,1074.660034,1199300,1074.660034,Decrease,1078.155029,6.989990
2019-01-10,1071.150024,1057.709961,1067.660034,1070.329956,1456400,1070.329956,Increase,1068.994995,2.669922

In [6]:


p=figure(x_axis_type='datetime',width=1000,height=500)

p.title.text="Finace Chart"




hours_12=12*60*60*1000

p.segment(df.index,df.Open,df.index,df.Close,line_color="black")

p.rect(df.index[df.Status=="Increase"],df.Middle[df.Status=="Increase"],
       hours_12,df.Hight[df.Status=="Increase"],fill_color="green",line_color="black")

p.rect(df.index[df.Status=="Decrease"],df.Middle[df.Status=="Decrease"],
       hours_12,df.Hight[df.Status=="Decrease"],fill_color="red ",line_color="black")

GlyphRenderer(id='1047', ...)

In [7]:
output_file("CS.html")

In [8]:
show(p)

ERROR:bokeh.core.validation.check:E-1001 (BAD_COLUMN_NAME): Glyph refers to nonexistent column name. This could either be due to a misspelling or typo, or due to an expected column being missing. : key "fill_color" value "red " [renderer: GlyphRenderer(id='1047', ...)]